// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\repository\machine_repository.go
//
// Generated by this command:
//
//	mockgen -source .\internal\repository\machine_repository.go -destination test/machine_repository_mocks.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/touutae-lab/vending-api/internal/database/vending_machine/vending_machine_service/model"
	gomock "go.uber.org/mock/gomock"
	context "golang.org/x/net/context"
)

// MockMachineRepository is a mock of MachineRepository interface.
type MockMachineRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMachineRepositoryMockRecorder
}

// MockMachineRepositoryMockRecorder is the mock recorder for MockMachineRepository.
type MockMachineRepositoryMockRecorder struct {
	mock *MockMachineRepository
}

// NewMockMachineRepository creates a new mock instance.
func NewMockMachineRepository(ctrl *gomock.Controller) *MockMachineRepository {
	mock := &MockMachineRepository{ctrl: ctrl}
	mock.recorder = &MockMachineRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMachineRepository) EXPECT() *MockMachineRepositoryMockRecorder {
	return m.recorder
}

// CreateMachine mocks base method.
func (m *MockMachineRepository) CreateMachine(ctx context.Context, machine model.Machine) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMachine", ctx, machine)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMachine indicates an expected call of CreateMachine.
func (mr *MockMachineRepositoryMockRecorder) CreateMachine(ctx, machine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMachine", reflect.TypeOf((*MockMachineRepository)(nil).CreateMachine), ctx, machine)
}

// DeleteMachine mocks base method.
func (m *MockMachineRepository) DeleteMachine(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMachine", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMachine indicates an expected call of DeleteMachine.
func (mr *MockMachineRepositoryMockRecorder) DeleteMachine(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMachine", reflect.TypeOf((*MockMachineRepository)(nil).DeleteMachine), ctx, id)
}

// GetAllMachine mocks base method.
func (m *MockMachineRepository) GetAllMachine(ctx context.Context) ([]model.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMachine", ctx)
	ret0, _ := ret[0].([]model.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMachine indicates an expected call of GetAllMachine.
func (mr *MockMachineRepositoryMockRecorder) GetAllMachine(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMachine", reflect.TypeOf((*MockMachineRepository)(nil).GetAllMachine), ctx)
}

// GetMachineByID mocks base method.
func (m *MockMachineRepository) GetMachineByID(ctx context.Context, id uuid.UUID) (model.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineByID", ctx, id)
	ret0, _ := ret[0].(model.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineByID indicates an expected call of GetMachineByID.
func (mr *MockMachineRepositoryMockRecorder) GetMachineByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineByID", reflect.TypeOf((*MockMachineRepository)(nil).GetMachineByID), ctx, id)
}

// UpdateMachine mocks base method.
func (m *MockMachineRepository) UpdateMachine(ctx context.Context, machine model.Machine) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMachine", ctx, machine)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMachine indicates an expected call of UpdateMachine.
func (mr *MockMachineRepositoryMockRecorder) UpdateMachine(ctx, machine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMachine", reflect.TypeOf((*MockMachineRepository)(nil).UpdateMachine), ctx, machine)
}
