// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\handler\product_handler_interface.go
//
// Generated by this command:
//
//	mockgen -source .\internal\handler\product_handler_interface.go -destination test/product_handler_mocks.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/touutae-lab/vending-api/internal/database/vending_machine/vending_machine_service/model"
	gomock "go.uber.org/mock/gomock"
	context "golang.org/x/net/context"
)

// MockProductHandlerInterface is a mock of ProductHandlerInterface interface.
type MockProductHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductHandlerInterfaceMockRecorder
}

// MockProductHandlerInterfaceMockRecorder is the mock recorder for MockProductHandlerInterface.
type MockProductHandlerInterfaceMockRecorder struct {
	mock *MockProductHandlerInterface
}

// NewMockProductHandlerInterface creates a new mock instance.
func NewMockProductHandlerInterface(ctrl *gomock.Controller) *MockProductHandlerInterface {
	mock := &MockProductHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockProductHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductHandlerInterface) EXPECT() *MockProductHandlerInterfaceMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductHandlerInterface) CreateProduct(ctx context.Context, product model.Product) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, product)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductHandlerInterfaceMockRecorder) CreateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductHandlerInterface)(nil).CreateProduct), ctx, product)
}

// DeleteProduct mocks base method.
func (m *MockProductHandlerInterface) DeleteProduct(ctx context.Context, id int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductHandlerInterfaceMockRecorder) DeleteProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductHandlerInterface)(nil).DeleteProduct), ctx, id)
}

// GetAllProduct mocks base method.
func (m *MockProductHandlerInterface) GetAllProduct(ctx context.Context) ([]model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProduct", ctx)
	ret0, _ := ret[0].([]model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProduct indicates an expected call of GetAllProduct.
func (mr *MockProductHandlerInterfaceMockRecorder) GetAllProduct(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProduct", reflect.TypeOf((*MockProductHandlerInterface)(nil).GetAllProduct), ctx)
}

// GetProductByID mocks base method.
func (m *MockProductHandlerInterface) GetProductByID(ctx context.Context, id int32) (model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductHandlerInterfaceMockRecorder) GetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductHandlerInterface)(nil).GetProductByID), ctx, id)
}

// UpdateProduct mocks base method.
func (m *MockProductHandlerInterface) UpdateProduct(ctx context.Context, product model.Product) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, product)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductHandlerInterfaceMockRecorder) UpdateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductHandlerInterface)(nil).UpdateProduct), ctx, product)
}
