//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Transaction struct {
	ID         int32 `sql:"primary_key"`
	MachineID  uuid.UUID
	ProductID  int32
	Quantity   int32
	TotalPrice float64
	OrderDate  time.Time
}
