//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Machinetype = newMachinetypeTable("vending_machine_service", "machinetype", "")

type machinetypeTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	Description postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type MachinetypeTable struct {
	machinetypeTable

	EXCLUDED machinetypeTable
}

// AS creates new MachinetypeTable with assigned alias
func (a MachinetypeTable) AS(alias string) *MachinetypeTable {
	return newMachinetypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MachinetypeTable with assigned schema name
func (a MachinetypeTable) FromSchema(schemaName string) *MachinetypeTable {
	return newMachinetypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MachinetypeTable with assigned table prefix
func (a MachinetypeTable) WithPrefix(prefix string) *MachinetypeTable {
	return newMachinetypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MachinetypeTable with assigned table suffix
func (a MachinetypeTable) WithSuffix(suffix string) *MachinetypeTable {
	return newMachinetypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMachinetypeTable(schemaName, tableName, alias string) *MachinetypeTable {
	return &MachinetypeTable{
		machinetypeTable: newMachinetypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newMachinetypeTableImpl("", "excluded", ""),
	}
}

func newMachinetypeTableImpl(schemaName, tableName, alias string) machinetypeTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		DescriptionColumn = postgres.StringColumn("description")
		allColumns        = postgres.ColumnList{IDColumn, DescriptionColumn}
		mutableColumns    = postgres.ColumnList{DescriptionColumn}
	)

	return machinetypeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Description: DescriptionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
