//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Transaction = newTransactionTable("vending_machine_service", "transaction", "")

type transactionTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	MachineID  postgres.ColumnString
	ProductID  postgres.ColumnInteger
	Quantity   postgres.ColumnInteger
	TotalPrice postgres.ColumnFloat
	OrderDate  postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TransactionTable struct {
	transactionTable

	EXCLUDED transactionTable
}

// AS creates new TransactionTable with assigned alias
func (a TransactionTable) AS(alias string) *TransactionTable {
	return newTransactionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TransactionTable with assigned schema name
func (a TransactionTable) FromSchema(schemaName string) *TransactionTable {
	return newTransactionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TransactionTable with assigned table prefix
func (a TransactionTable) WithPrefix(prefix string) *TransactionTable {
	return newTransactionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TransactionTable with assigned table suffix
func (a TransactionTable) WithSuffix(suffix string) *TransactionTable {
	return newTransactionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTransactionTable(schemaName, tableName, alias string) *TransactionTable {
	return &TransactionTable{
		transactionTable: newTransactionTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newTransactionTableImpl("", "excluded", ""),
	}
}

func newTransactionTableImpl(schemaName, tableName, alias string) transactionTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		MachineIDColumn  = postgres.StringColumn("machine_id")
		ProductIDColumn  = postgres.IntegerColumn("product_id")
		QuantityColumn   = postgres.IntegerColumn("quantity")
		TotalPriceColumn = postgres.FloatColumn("total_price")
		OrderDateColumn  = postgres.TimestampColumn("order_date")
		allColumns       = postgres.ColumnList{IDColumn, MachineIDColumn, ProductIDColumn, QuantityColumn, TotalPriceColumn, OrderDateColumn}
		mutableColumns   = postgres.ColumnList{MachineIDColumn, ProductIDColumn, QuantityColumn, TotalPriceColumn, OrderDateColumn}
	)

	return transactionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		MachineID:  MachineIDColumn,
		ProductID:  ProductIDColumn,
		Quantity:   QuantityColumn,
		TotalPrice: TotalPriceColumn,
		OrderDate:  OrderDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
